Watching for file changes with StatReloader

def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def send_invitation_email(invitation_id, invited_user_language):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1

Validating data: {'board': <Board: bord test>, 'invited_user_email': 'mojtaba.cy@gmail.com'}
Searching for user with email: mojtaba.cy@gmail.com
Found user: moj
Request data: {'board': 41, 'invited_user_email': 'mojtaba.cy@gmail.com'}
Found board: bord test
Invited user: moj
Internal Server Error: /invitations/
Traceback (most recent call last):
  File "/home/osboxes/projects/trelloProject/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 991, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/home/osboxes/projects/trelloProject/.venv/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/osboxes/projects/trelloProject/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 661, in create
    obj = self.model(**kwargs)
  File "/home/osboxes/projects/trelloProject/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 569, in __init__
    raise TypeError(
    ...<2 lines>...
    )
TypeError: Invitation() got unexpected keyword arguments: 'invited_user_email'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/osboxes/projects/trelloProject/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/osboxes/projects/trelloProject/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/osboxes/projects/trelloProject/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/osboxes/projects/trelloProject/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/osboxes/projects/trelloProject/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/home/osboxes/projects/trelloProject/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/osboxes/projects/trelloProject/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/osboxes/projects/trelloProject/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/osboxes/projects/trelloProject/.venv/lib/python3.13/site-packages/rest_framework/generics.py", line 246, in post
    return self.create(request, *args, **kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/osboxes/projects/trelloProject/.venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/osboxes/projects/trelloProject/trello/invitations/views.py", line 51, in perform_create
    invitation = serializer.save(board=board)
  File "/home/osboxes/projects/trelloProject/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/osboxes/projects/trelloProject/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1010, in create
    raise TypeError(msg)
TypeError: Got a `TypeError` when calling `Invitation.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `Invitation.objects.create()`. You may need to make the field read-only, or override the InvitationSerializer.create() method to handle this correctly.
Original exception was:
 Traceback (most recent call last):
  File "/home/osboxes/projects/trelloProject/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 991, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/home/osboxes/projects/trelloProject/.venv/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/osboxes/projects/trelloProject/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 661, in create
    obj = self.model(**kwargs)
  File "/home/osboxes/projects/trelloProject/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 569, in __init__
    raise TypeError(
    ...<2 lines>...
    )
TypeError: Invitation() got unexpected keyword arguments: 'invited_user_email'

/home/osboxes/projects/trelloProject/trello/invitations/serializers.py changed, reloading.
Watching for file changes with StatReloader
/home/osboxes/projects/trelloProject/trello/invitations/models.py changed, reloading.
Watching for file changes with StatReloader
/home/osboxes/projects/trelloProject/trello/invitations/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Validating data: {'board': <Board: bord test>, 'invited_user_email': 'mojtaba.cy@gmail.com'}
Searching for user with email: mojtaba.cy@gmail.com
Found user: moj
Request data: {'board': 41, 'invited_user_email': 'mojtaba.cy@gmail.com'}
Found board: bord test
Invited user: moj
Creating invitation with validated_data: {'board': <Board: bord test>, 'invited_user': <User: moj>}
Created invitation: Invitation to bord test for moj

def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def send_invitation_email(invitation_id, invited_user_language):
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def backend_cleanup():
    return 1

Start from server, version: 0.9, properties: {'capabilities': {'publisher_confirms': True, 'exchange_exchange_bindings': True, 'basic.nack': True, 'consumer_cancel_notify': True, 'connection.blocked': True, 'consumer_priorities': True, 'authentication_failure_close': True, 'per_consumer_qos': True, 'direct_reply_to': True}, 'cluster_name': 'rabbit@osboxes', 'copyright': 'Copyright (c) 2007-2024 Broadcom Inc and/or its subsidiaries', 'information': 'Licensed under the MPL 2.0. Website: https://rabbitmq.com', 'platform': 'Erlang/OTP 27.3', 'product': 'RabbitMQ', 'version': '4.0.5'}, mechanisms: [b'AMQPLAIN', b'ANONYMOUS', b'PLAIN'], locales: ['en_US']
using channel_id: 1
Channel open
Watching for file changes with StatReloader
Unauthorized: /users/test-translation/
Unauthorized: /boards/
Not Found: /favicon.ico
